name: Get security advise from Thoth
on:
  push:
    paths:
      - "setup.cfg"
jobs:
  validate-dependencies:
    runs-on: ubuntu-latest
    container: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
    name: Get Thoth recommendations on your dependencies
    steps:
      - uses: actions/checkout@v3
      - name: Get Thoth security advisories
        id: thoth-advise
        uses: thoth-station/thoth-github-action@v0.0.0
        with:
          requirements-path: "setup.cfg"
          requirements-format: setup.cfg
